""" 
Function untuk membersihkan data text
"""
import re
import sqlite3
import pandas as pd

# Membuat list kata alay dan abusive dari database 'gold_challenge.db'
conn = sqlite3.connect('gold_challenge.db')
abusive_words = pd.read_sql('SELECT * FROM abusive', conn)
alay_words = pd.read_sql('SELECT * from alay', conn)
list_abusive = abusive_words.values.tolist()
list_alay = alay_words.values.tolist()

def text_cleansing(text):
    # Bersihkan tanda baca (selain huruf dan angka)
    clean_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    # Bersihkan kata kasar
    clean_text = re.sub(r'anjing', '***', clean_text).lower()
    clean_text = re.sub(r'alay', '***', clean_text).lower()
    clean_text = re.sub(r'ampas', '***', clean_text).lower()
    clean_text = re.sub(r'buta', '***', clean_text).lower()
    clean_text = re.sub(r'keparat', '***', clean_text).lower()
    clean_text = re.sub(r'anjir', '***', clean_text).lower()
    clean_text = re.sub(r'babi', '***', clean_text).lower()
    clean_text = re.sub(r'bacot', '***', clean_text).lower()
    clean_text = re.sub(r'bajingan', '***', clean_text).lower()
    clean_text = re.sub(r'banci', '***', clean_text).lower()
    clean_text = re.sub(r'bandot', '***', clean_text).lower()
    clean_text = re.sub(r'buaya', '***', clean_text).lower()
    clean_text = re.sub(r'bangkai', '***', clean_text).lower()
    clean_text = re.sub(r'bangsat', '***', clean_text).lower()
    clean_text = re.sub(r'bego', '***', clean_text).lower()
    clean_text = re.sub(r'bejat', '***', clean_text).lower()
    clean_text = re.sub(r'bencong', '***', clean_text).lower()
    clean_text = re.sub(r'berak', '***', clean_text).lower()
    clean_text = re.sub(r'bisu', '***', clean_text).lower()
    clean_text = re.sub(r'celeng', '***', clean_text).lower()
    clean_text = re.sub(r'jancuk', '***', clean_text).lower()
    clean_text = re.sub(r'bodoh', '***', clean_text).lower()
    clean_text = re.sub(r'berengsek', '***', clean_text).lower()
    clean_text = re.sub(r'brengsek', '***', clean_text).lower()
    clean_text = re.sub(r'budek', '***', clean_text).lower()
    clean_text = re.sub(r'burik', '***', clean_text).lower()
    clean_text = re.sub(r'jamban', '***', clean_text).lower()
    clean_text = re.sub(r'cocot', '***', clean_text).lower()
    clean_text = re.sub(r'congor', '***', clean_text).lower()
    clean_text = re.sub(r'culun', '***', clean_text).lower()
    clean_text = re.sub(r'cupu', '***', clean_text).lower()
    clean_text = re.sub(r'dongok', '***', clean_text).lower()
    clean_text = re.sub(r'dongo', '***', clean_text).lower()
    clean_text = re.sub(r'dungu', '***', clean_text).lower()
    clean_text = re.sub(r'edan', '***', clean_text).lower()
    clean_text = re.sub(r'tai', '***', clean_text).lower()
    clean_text = re.sub(r'ngewe', '***', clean_text).lower()
    clean_text = re.sub(r'geblek', '***', clean_text).lower()
    clean_text = re.sub(r'goblok', '***', clean_text).lower()
    clean_text = re.sub(r'gembel', '***', clean_text).lower()
    clean_text = re.sub(r'gila', '***', clean_text).lower()
    clean_text = re.sub(r'iblis', '***', clean_text).lower()
    clean_text = re.sub(r'setan', '***', clean_text).lower()
    clean_text = re.sub(r'idiot', '***', clean_text).lower()
    clean_text = re.sub(r'jablay', '***', clean_text).lower()
    clean_text = re.sub(r'jembud', '***', clean_text).lower()
    clean_text = re.sub(r'jembut', '***', clean_text).lower()
    clean_text = re.sub(r'jijik', '***', clean_text).lower()
    clean_text = re.sub(r'kacrut', '***', clean_text).lower()
    clean_text = re.sub(r'kafir', '***', clean_text).lower()
    clean_text = re.sub(r'modar', '***', clean_text).lower()
    clean_text = re.sub(r'kampang', '***', clean_text).lower()
    clean_text = re.sub(r'kampret', '***', clean_text).lower()
    clean_text = re.sub(r'kampungan', '***', clean_text).lower()
    clean_text = re.sub(r'kimak', '***', clean_text).lower()
    clean_text = re.sub(r'kontol', '***', clean_text).lower()
    clean_text = re.sub(r'kunti', '***', clean_text).lower()
    clean_text = re.sub(r'tuyul', '***', clean_text).lower()
    clean_text = re.sub(r'kunyuk', '***', clean_text).lower()
    clean_text = re.sub(r'mampus', '***', clean_text).lower()
    clean_text = re.sub(r'memek', '***', clean_text).lower()
    clean_text = re.sub(r'monyet', '***', clean_text).lower()
    clean_text = re.sub(r'najis', '***', clean_text).lower()
    clean_text = re.sub(r'nete', '***', clean_text).lower()
    clean_text = re.sub(r'ngentot', '***', clean_text).lower()
    clean_text = re.sub(r'noob', '***', clean_text).lower()
    clean_text = re.sub(r'pecun', '***', clean_text).lower()
    clean_text = re.sub(r'perek', '***', clean_text).lower()
    clean_text = re.sub(r'sampah', '***', clean_text).lower()
    clean_text = re.sub(r'sarap', '***', clean_text).lower()
    clean_text = re.sub(r'setan', '***', clean_text).lower()
    clean_text = re.sub(r'biadab', '***', clean_text).lower()
    clean_text = re.sub(r'tolol', '***', clean_text).lower()
    clean_text = re.sub(r'silit', '***', clean_text).lower()
    clean_text = re.sub(r'bokong', '***', clean_text).lower()
    clean_text = re.sub(r'sinting', '***', clean_text).lower()
    clean_text = re.sub(r'sompret', '***', clean_text).lower()
    clean_text = re.sub(r'sontoloyo', '***', clean_text).lower()
    clean_text = re.sub(r'terkutuk', '***', clean_text).lower()
    clean_text = re.sub(r'titit', '***', clean_text).lower()
    clean_text = re.sub(r'pantat', '***', clean_text).lower()
    clean_text = re.sub(r'tolol', '***', clean_text).lower()
    clean_text = re.sub(r'udik', '***', clean_text).lower()
    clean_text = re.sub(r'antek', '***', clean_text).lower()
    clean_text = re.sub(r'asing', '***', clean_text).lower()
    clean_text = re.sub(r'ateis', '***', clean_text).lower()
    clean_text = re.sub(r'sitip', '***', clean_text).lower()
    clean_text = re.sub(r'autis', '***', clean_text).lower()
    clean_text = re.sub(r'sinting', '***', clean_text).lower()
    clean_text = re.sub(r'picek', '***', clean_text).lower()
    clean_text = re.sub(r'ayam kampus', '***', clean_text).lower()
    clean_text = re.sub(r'bani kotak', '***', clean_text).lower()
    clean_text = re.sub(r'bispak', '***', clean_text).lower()
    clean_text = re.sub(r'bisyar', '***', clean_text).lower()
    clean_text = re.sub(r'bokep', '***', clean_text).lower()
    clean_text = re.sub(r'bong', '***', clean_text).lower()
    clean_text = re.sub(r'cacat', '***', clean_text).lower()
    clean_text = re.sub(r'cct', '***', clean_text).lower()
    clean_text = re.sub(r'cebong', '***', clean_text).lower()
    clean_text = re.sub(r'taplak', '***', clean_text).lower()
    clean_text = re.sub(r'cungkring', '***', clean_text).lower()
    clean_text = re.sub(r'gay', '***', clean_text).lower()
    clean_text = re.sub(r'gembrot', '***', clean_text).lower()
    clean_text = re.sub(r'lesbi', '***', clean_text).lower()
    clean_text = re.sub(r'culun', '***', clean_text).lower()
    clean_text = re.sub(r'cupu', '***', clean_text).lower()
    clean_text = re.sub(r'gendut', '***', clean_text).lower()
    clean_text = re.sub(r'hina', '***', clean_text).lower()
    clean_text = re.sub(r'homo', '***', clean_text).lower()
    clean_text = re.sub(r'komunis', '***', clean_text).lower()
    clean_text = re.sub(r'koreng', '***', clean_text).lower()
    clean_text = re.sub(r'krempeng', '***', clean_text).lower()
    clean_text = re.sub(r'lengser', '***', clean_text).lower()
    clean_text = re.sub(r'lgbt', '***', clean_text).lower()
    clean_text = re.sub(r'lonte', '***', clean_text).lower()
    clean_text = re.sub(r'mucikari', '***', clean_text).lower()
    clean_text = re.sub(r'munafik', '***', clean_text).lower()
    clean_text = re.sub(r'ngaceng', '***', clean_text).lower()
    clean_text = re.sub(r'nista', '***', clean_text).lower()
    clean_text = re.sub(r'kejam', '***', clean_text).lower()
    clean_text = re.sub(r'onta', '***', clean_text).lower()
    clean_text = re.sub(r'panastak', '***', clean_text).lower()
    clean_text = re.sub(r'mokondo', '***', clean_text).lower()
    clean_text = re.sub(r'jablay', '***', clean_text).lower()
    clean_text = re.sub(r'panasbung', '***', clean_text).lower()
    clean_text = re.sub(r'bani', '***', clean_text).lower()
    clean_text = re.sub(r'pasukan nasi', '***', clean_text).lower()
    clean_text = re.sub(r'porno', '***', clean_text).lower()
    clean_text = re.sub(r'seks', '***', clean_text).lower()
    clean_text = re.sub(r'rejim', '***', clean_text).lower()
    clean_text = re.sub(r'rezim', '***', clean_text).lower()
    clean_text = re.sub(r'sange', '***', clean_text).lower()
    clean_text = re.sub(r'serbet', '***', clean_text).lower()
    clean_text = re.sub(r'sipit', '***', clean_text).lower()
    clean_text = re.sub(r'transgender', '***', clean_text).lower()
    
    #Bersihkan kata alay
    clean_text = " ".join(dict(zip(alay_words['alay_word'],alay_words['formal_word'])).get(word, word) for word in clean_text.split())
    return clean_text

def cleansing_files(file_upload):
    # Read csv file upload, jika error dengan metode biasa, gunakan encoding latin-1
    try:
        df_upload = pd.read_csv(file_upload)
    except:
        df_upload = pd.read_csv(file_upload, encoding="latin-1")
    print("Read dataframe from Upload success!")
    # Ambil hanya kolom pertama saja 
    df_upload = pd.DataFrame(df_upload.iloc[:,0])
    # Rename kolom menjadi "raw_text"
    df_upload.columns = ["raw_text"]
    # Bersihkan text menggunakan fungsi text_cleansing
    # Simpan di kolom "clean_text"
    df_upload["clean_text"] = df_upload["raw_text"].apply(text_cleansing)
    print("Cleansing text success!")
    return df_upload